- hosts: aws_controller
  gather_facts: no
  remote_user: root
  become: yes
  vars:
    ansible_host_key_checking: false
    pod_network_cidr: 192.168.10.0/21
  tasks:
    - name: Create cluster
      shell: |
        kubeadm reset -f
        kubeadm init --pod-network-cidr="{{pod_network_cidr}}"
      register: init_output
    - name: Split output by newline
      set_fact:
        cluster_init: "{{init_output.stdout | split('\n')}}"
    - name: Execute mkdir, cp, and chown commands
      shell:
        cmd: "{{item}}"
      with_items: "{{cluster_init}}"
      when: "'mkdir' in item or 'sudo' in item"
    - name: Find kubeadm join command
      delegate_to: localhost
      become: no
      set_fact:
        kubeadm_join_command: "{{ ( item+next_item ) | replace('\\\t','') }}"
      with_items: "{{cluster_init}}"
      when: "'kubeadm' in item and arr_index < (cluster_init | length) - 1"
      loop_control:
        index_var: arr_index
      vars:
        next_item: "{{cluster_init[arr_index + 1]}}"
    - name: Update kudeadm command to add.yaml
      delegate_to: localhost
      become: no
      replace:
        path: ./workers.yaml
        regexp: '        cmd:'
        replace: '        cmd: "{{kubeadm_join_command}}"'
    - name: Remove Taints
      shell:
        cmd: kubectl taint nodes --all node-role.kubernetes.io/master-
    - name: Install Calico pod network add-on
      shell:
        cmd: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
    - name: Get pods
      shell: |
        kubectl get pods --all-namespaces
      register: get_pods
    - name: Display results of initial pods
      debug: 
        msg: "{{ get_pods.stdout_lines }}"
    - name: Unset cluster_init set_fact
      set_fact:
        cluster_init: null
      when: cluster_init is defined