- hosts: aws_workers
  gather_facts: no
  remote_user: root
  become: yes
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Add node to AWS Kubnernetes cluster
      shell: 
        cmd:
      register: test_host
    - name: 