- hosts: controllers
  gather_facts: no
  remote_user: root
  become: yes
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Echo Hostname
      shell: 
        cmd: echo "Testing controllers" && hostname
      register: test_host
    - debug: var=test_host.stdout_lines
    # run ./scripts/aws/controller_node.sh
    # get and write add_node_cmmnd to worker_node.sh