all:
  children:
    aws:
      vars:
        ansible_port: 22
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ./ansible/aws/k8s.pem
      hosts:
        aws_controller:
          ansible_host: 44.201.175.238
      children:
        aws_workers:
          hosts:
            aws_worker1:
              ansible_host: 44.203.93.173
            aws_worker2:
              ansible_host: 54.211.6.151
